apiVersion: valkey.my.domain/v1
kind: ValkeyNode
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkeynode-sample
spec:
  # TODO(user): Add fields here
